# Allure Configuration
allure.results.directory=target/allure-results
allure.link.issue.pattern=https://example.com/issues/{}
allure.link.tms.pattern=https://example.com/tms/{}
allure.link.mylink.pattern=https://example.com/mylink/{}

# Allure Environment Properties
allure.environment=test
allure.browser.name=chrome
allure.browser.version=latest
allure.os.name=macOS
allure.os.version=14.6.0
